name: make_docs

on:
  push:
    branches: 
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-jupyter
          pip install pillow cairosvg

      - name: Copy notebooks to docs
        run: cp *.ipynb docs/

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
